package URLReaderApp;


/**
* URLReaderApp/URLReaderOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Thursday, 14 April, 2022 11:10:17 AM IST
*/

public interface URLReaderOperations 
{
  int urlbytes (String url);
  void shutdown ();
} // interface URLReaderOperations
