package URLReaderApp;


/**
* URLReaderApp/URLReader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Thursday, 14 April, 2022 11:10:17 AM IST
*/

public interface URLReader extends URLReaderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface URLReader
