package URLReaderApp;


/**
* URLReaderApp/URLReaderHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Thursday, 14 April, 2022 11:10:17 AM IST
*/

abstract public class URLReaderHelper
{
  private static String  _id = "IDL:URLReaderApp/URLReader:1.0";

  public static void insert (org.omg.CORBA.Any a, URLReaderApp.URLReader that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static URLReaderApp.URLReader extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (URLReaderApp.URLReaderHelper.id (), "URLReader");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static URLReaderApp.URLReader read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_URLReaderStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, URLReaderApp.URLReader value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static URLReaderApp.URLReader narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof URLReaderApp.URLReader)
      return (URLReaderApp.URLReader)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      URLReaderApp._URLReaderStub stub = new URLReaderApp._URLReaderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static URLReaderApp.URLReader unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof URLReaderApp.URLReader)
      return (URLReaderApp.URLReader)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      URLReaderApp._URLReaderStub stub = new URLReaderApp._URLReaderStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
